spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: ture
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/gaeckso_db?useUnicode=ture&characterEncoding=UTF-8
    username: root
    password: 1308
    driver-class-name: com.mysql.cj.jdbc.Driver
